name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libudev-dev gdb-multiarch minicom binutils-arm-none-eabi
        version: 1.0
    - name: Update rust toolshain and install component
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: llvm-tools-preview
        target: thumbv7em-none-eabihf
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Convert to hex
      run: objcopy -O ihex ./target/thumbv7em-none-eabihf/release/fantastic-disco fantastic-disco.hex
    - name: Move file
      run: |
        mkdir firm
        cp ./target/thumbv7em-none-eabihf/release/fantastic-disco ./firm
        cp ./fantastic-disco.hex            ./firm
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firm-${{ github.sha }}
        path: ./firm # TODO: ファイルを記述
