name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with: 
        python-version: '3.6.15'
    - uses: BSFishy/pip-action@v1
      with: 
        packages: |
          intelhex
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libudev-dev gdb-multiarch minicom
        version: 1.0
    - name: Update rust toolshain and install component
      run: |
          rustup component add llvm-tools-preview
          rustup target add thumbv7em-none-eabihf
          rustup update
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Convert to hex
      run: python bin2hex.py ./target/thumbv7em-none-eabihf/release/fantastic-disco ./fantastic-disco.hex
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firm-${{ github.sha }}
        path: ./fantastic-disco.hex # TODO: ファイルを記述
