name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Cargo.toml'
      - '.github/workflows/*.*'
      - '**/*.rs'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: binutils-arm-none-eabi # libudev-dev gdb-multiarch minicom
        version: 1.0
    - name: Update rust toolshain and install component
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: thumbv7em-none-eabihf
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Convert to hex
      run: objcopy -O ihex ./target/thumbv7em-none-eabihf/release/fantastic-disco ./fantastic-disco.hex
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firm-${{ github.sha }}
        path: fantastic-disco.hex
